### ISSUE TITLE
Code-related articles

### ISSUE THREAD

**Issue by petrolworker** [liufeng2317/TorchInversion#1]
Hi Liu Feng,

Thank you for sharing the code. I find your work very interesting. Is there a paper that provides more detailed description? Which paper should I cite when using your code?

**Comment by liufeng2317** [comment]
Hello Adam,

Thanks for your interest in my recent work. We've been continuously revising and refining our work on ADFWI, and the latest version will be available within two months. This latest iteration will feature full waveform inversion of acoustic and elastic waves based on automatic differentiation. Additionally, we're in the process of preparing a related article, the preprint version of which will be released earlier.

Best regards
